checkoutLocation: "/workspace/go/src/github.com/hpssjellis/gitpod-hello-ui-demo"
workspaceLocation: /
image:
  file: Dockerfile
ports:
  - port: 6080
    protocol: "http"
tasks: 
  - command cd /workspace/go/src/github.com/hpssjellis/gitpod-hello-ui-demo  && 
      go get -v ./... &&
      go build -o app &&
      ./app
