checkoutLocation: src/github.com/hpssjellis/gitpod-hello-ui-demo

workspaceLocation: /

image:
  file: Dockerfile
  
ports:
  - port: 6080
    onOpen: open-preview
    
tasks:
  - command: "go get -v ./... && cd /workspace/go && go run ../src/github.com/hpssjellis/gitpod-hello-ui-demo/main.go"
  
  
  
  
  
