checkoutLocation: src/github.com/32leaves/hello-ui
workspaceLocation: /
image:
  file: Dockerfile
ports:
  - port: 6080
    protocol: "http"
tasks: 
  - command cd /workspace/src/github.com/32leaves/hello-ui/  && 
    go run main.go
