checkoutLocation: src/github.com/hpssjellis/gitpod-hello-ui-demo

workspaceLocation: /

image:
  file: Dockerfile
  
ports:
  - port: 6080
    protocol: "http"
    
tasks:
  - command: "go get -v ./... "
  - command: gp preview $(gp url 6080)                                                  &&
             go run /workspace/src/github.com/hpssjellis/gitpod-hello-ui-demo/main.go
  
  
  # not getting the following working from the .gitpod.yml file, but it works fine from the command line
  # go run /workspace/src/github.com/hpssjellis/gitpod-hello-ui-demo/main.go 

  
  
